### ISSUE TITLE
The purpose of remove the * , & and  << opeartors

### ISSUE THREAD

**Issue by eyauwag** [jasondelaat/pymonad#10]
I see that in the rev 1.x, pymonad supports the *, & and << operators and the * for function composition.  And these notations are so common in the haskell.  They indeed made the code more readable and looks more functional.  But in the rev 2.x, they are moved to the operator folder and will be remove in the future. 
I don't understand the purpose of the removement. Would you please do some explaination?

**Comment by jasondelaat** [comment]
I explained this a little bit in this closed issue: #9 

Briefly though, the semantics of pymonad operators didn't really have anything to do with the "normal" semantics people usually associate with those operators. In pymonad, * doesn't have anything to do with multiplication for instance. So the use of operators in this fashion just generally goes against "good" python coding style, which is why their use is discouraged.

However, the operators will most likely ***not*** be removed but will remain in the operators package. So you're free to use them as much as you'd like.

The general guideline that I'd suggest is this: If you're writing code that other people will have to edit at some point, especially if they're not necessarily familiar with Haskell and/or functional programming, then avoid using the operators. If you're the only one that will ever touch the code and you prefer the operators, go for it. But, of course, you're free to do whatever you'd like.

Hope that helps!
