### ISSUE TITLE
Why is Either catching exceptions?

### ISSUE THREAD

**Issue by PyAntony** [jasondelaat/pymonad#13]
Hi,

I have bee using the Either class at work and I have encountered this weird behavior. Basically when you map/bind and an exception is raised it is catched and a Left object is returned instead. I find this behavior annoying; I would prefer for the exception to just be raised so I can easily debug the issue. For what I've seen in other libraries a Try monad is more appropriate to catch the error if any is raised, not the Either class. Example:
```Python
def raise_exception():
    raise Exception

left = Right(100).map(lambda x: raise_exception())
```
Above code doesn't raise an exception, just returns a Left object. Is this behavior happening by design? It really makes debugging a lot harder.

**Comment by jasondelaat** [comment]
You're right, Either really shouldn't be doing that, that's not it's job. I've fixed it and bumped the version to 2.3.4 here and on PyPi. 

My thinking was that since most examples of Either use it as an error catching mechanism why not just automatically catch errors? But that's not really what the semantics of Either are or should be. I hate it when programmers try to be clever and solve my problems for me, thereby creating more problems so, of course, I did the same thing. Thanks for bringing this up.

**Comment by PyAntony** [comment]
Thank you! this is great, it does help a lot.

**Comment by efagerberg** [comment]
Interesting, I too have only seen the Either monad described as automatically handling the error and passing a left. Is there a plan to add a Try monad? Seems a little redundant to still have to write error handling code explicitly.

**Comment by jasondelaat** [comment]
I hadn't really considered adding a Try monad but it's something I can look into. I think the above issue though was more about actual errors rather than exceptional conditions that might occur as a natural part of execution. For instance:

``` python
def some_func(x)
    return x+'1'

Either.insert(1).then(some_func)
```

`some_func` will throw a TypeError and the old implementation of Either would catch that and wrap it in a Left. But this isn't input we don't know how to handle or some condition we want to check for, it's an actual error cause by a brain-fart/typo/whatever. The solution isn't to add a `try` block around it, the solution is to fix the function.

``` python
def some_func(x):
    return x+1
```

But the old implementation made finding this kind of error difficult because the program wouldn't fail even though it should.

**Comment by PyAntony** [comment]
A Try Monad is much needed. Try/except really pollutes the code a lot.

**Comment by efagerberg** [comment]
Yeah I agree that Either should be constrained to just representing two potential distinct values.

**Comment by jasondelaat** [comment]
Okay, I'll put Try on my todo list.
There's already exception handling implemented in Promise so doing essentially the same thing but without concurrency should be fairly straight-forward.
