### ISSUE TITLE
Getting the error from the Error

### ISSUE THREAD

**Issue by openbrian** [jasondelaat/pymonad#3]
I'm liking the Either Result or Error monad.  How about something like this?

```
class _Error(Either[M, T]):
    def __repr__(self):
        return f'Result: {self.value}' if self.is_right() else f'Error: {self.monoid[0]}'
    def value(self):
        return self.monoid[0]
```

**Comment by jasondelaat** [comment]
Hey, not a bad idea to offer a way to get an error value out of the monad instance though just directly pulling it out sort of goes against the idea of monads where it's easy to put values in but less straight-forward to get values out. 

I think though it wouldn't be a bad idea to offer a functionality similar to the [either](https://hackage.haskell.org/package/base-4.14.0.0/docs/Data-Either.html#v:either) function in haskell but as a method. Basically we give an either value two functions: one if it's a Right (or Result) value and one if it's a Left (or Error). We don't need to know which type of value it is and the function for the Error value can have a try/except block so you can deal with whatever types of errors you might end up with.

So hypothetically:

```
def error_func(e):
    try:
        raise e
    except TypeError:
        print('Caught TypeError')

def result_func(r):
    print(f'Got result {r}')
    
err = Error(TypeError('TypeError'))
err.either(error_func, result_func)

res = Result(6)
res.either(error_func, result_func)
```

Of course you don't have to raise the error you could just examine it and do whatever you want. I think that's a bit cleaner than just trying to access the error directly since trying to get an error out of a Result value would be problematic as would attempting to get a result our of an Error. 

What do you think of a solution along those lines? Would that serve your purposes? I could do something similar for the Maybe types as well.

**Comment by openbrian** [comment]
Hey Jason,  I was introduced to monads with Rust, not Haskell.  Though Professor Hutton uses Haskell for demos (https://www.youtube.com/watch?v=t1e8gqXLbsU).  I just want to write my python with type hints, no nulls, and no exceptions.

To avoid exceptions, I wrote a function lift() which I saw in some other monad package (module, file).  Which takes a function that may through an exception and converts it into a Result.

It's obviously hard to get the value out of a monad, and I begin to understand that is by design.  I don't really like doing this:

```
if not result.is_right():
    print('it failed')
    exit(3)
value = result.value
```

I like your idea much better.  I have some exposure to that with JavaScript Promises .then().  I look forward to exploring this more.

Let me know if I can help with your documentation repository.  For now I can provide use cases in real world applications.

**Comment by jasondelaat** [comment]
Hi Brian,
For the documentation  repository: Yes please! I seem to never find the time to add content over there and I really, really need to. If you're willing to write something up or even just offer some suggestions of articles that you'd like to see I would greatly appreciate it!

I'm not sure I like the name 'either' as the method for extracting a value but I'm also not sure it's a bad name. And similarly for a 'maybe' method on Maybe. I'll give it some thought and see if better names occur to me. I should have an implementation up in a couple of days once I have a bit of time. Thanks for opening this up

**Comment by openbrian** [comment]
I remember seeing Michael Feathers use either in this talk.  He's writing Ruby, but cites Haskell.

I assume this is the sort of pipeline you refer to, by passing the error along to the next method in the chain.

https://youtu.be/AnZ0uTOerUI?t=1694  The whole guitar fret example starts at 19:35.

**Comment by openbrian** [comment]
For reference https://gist.github.com/michaelfeathers/386052a620d9fc70bd16, he writes up the either monad himself in this gist.

**Comment by jasondelaat** [comment]
Yeah exactly. It frees us up from having to deal with errors immediately and let's us defer error handling to a time of our choosing. 

The main benefit, to my way of thinking anyway, is that we get a piece of code that is flat and completely straight-forward. We can easily see the steps of the algorithm because it's not polluted with the nitty-gritty of error handling at each step. Instead, we can deal with the error at the end of the process, or at least whenever makes the most sense, before continuing on.

But yeah, you basically stay inside the Either (or Error since they're just aliases for each other) monad as much as possible and then you can use the 'either' method, which I'm proposing here, to actually deal with the error or further process the result.

**Comment by jasondelaat** [comment]
Worth noting that, in the video, when he uses 'either' he's basically talking about the Either type. So, equivalent to the Either _class_ in pymonad.

And I'm talking about an either _method_ which extracts a value from an Either object.

Just wanted to make that clear because we're ending up with a whole lot of different things that all have the same name.

**Comment by openbrian** [comment]
Yeah, I see he creates _join_ -- maybe not a good name -- to return either the errors or the result.

**Comment by jasondelaat** [comment]
Okay so I've added the 'either' method to the Either class. It takes two functions, the first function is called if the Either object is a Left (or Error) and the second function is called if the Either object is a Right (or Result).

```python
Left(1).either(lambda i: i + 1, lambda i: i * 10)
```
Should output 2.

While
```python
Right(1).either(lambda i: i + 1, lambda i: i * 10)
```
Should output 10.

I've also added a similar method on the Maybe class (creatively called 'maybe' with alias 'option') which does basically the same thing. Instead of two functions it takes a default value and a function. The default value is returned if the Maybe object is Nothing and the function is called if the Maybe object is a Just (or Option).

```python
Nothing.maybe(0, lambda i: i + 1)
```
Outputs 0, and
```python
Just(1).maybe(0, lambda i: i + 1)
```
outputs 2.
