### ISSUE TITLE
Bind operator does not work

### ISSUE THREAD

**Issue by efagerberg** [jasondelaat/pymonad#9]
Pymonad version: 2.3.1
Python version: 3.8.6

```python
from pymonad.maybe import Just

def add2(x):
    return Just(x + 2)

print((Just(3) >> add2).value)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for >>: 'Maybe' and 'function'

dir(Just(3))
['__class__', '__class_getitem__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__orig_bases__', '__parameters__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_is_protocol', 'amap', 'apply', 'bind', 'insert', 'is_just', 'is_nothing', 'join', 'map', 'maybe', 'monoid', 'option', 'then', 'value']
```

Notice that there is no `__rshift__` function

**Comment by jasondelaat** [comment]
Yeah, in version 2 I wanted to discourage the use of operators. They're still available if you really want to use them, just change your import to

~~~python
from pymonad.operators.maybe import Just
~~~

and everything should work properly. 

You might also like to know that I've added a 'maybe' method so rather than accessing the value directly you can extract a value from a Maybe or return a default value if the value is Nothing. It takes a default value and a function.

Something like this:

~~~python
from pymonad.operators.maybe import Just

def add2(x):
    return Just(x + 2)

print((Just(3) >> add2).maybe(0, lambda x: x))
~~~

So if the value was Nothing that would print 0 and otherwise it returns the value inside the Just. Obviously you can use any function there not just that one.

I should really put that stuff in the README and do a better job with the documentation. I'll try to set some time aside to do that so other people don't keep running into the same problem. Thanks for pointing it out!

**Comment by efagerberg** [comment]
Thanks for the explanation. Agreed more documentation would be really helpful. I will close this for now.

**Comment by jasondelaat** [comment]
I've updated the README with a section on upgrading from 1.3. It has a few other things that have changed that are probably worth knowing about. Hopefully it helps until I can dedicate more time to the documentation proper.

**Comment by efagerberg** [comment]
Just curious, why are you discouraging the usage of those operators?

**Comment by jasondelaat** [comment]
The general advice for operator overloading, not just in python but any language that supports it, is not to overload the semantics of the operator. In other words, if you're overloading the * operator then the thing that you're doing should be at least plausibly related to multiplication. None of pymonad's operators adhere to this rule of thumb which creates an extra barrier to understanding the code. Also, stringing together a bunch of terms via operators has the danger of just turning into a bunch of line noise which makes code harder to read in general and would probably be considered "un-pythonic." 

Anyway I'd say in general if you're writing code that other people are going to have to look at, avoid using the operators. But sometimes operators are handy for doing something concisely and if you're the only one who's ever going to have to deal with the code, then go nuts!
